### ISSUE TITLE
VPM: Minimum required: 0.00001000 BTC, need -0.00080223 BTC more

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#193]
After a new BTC block was found several VPM's showed this error on the automine trigger (after a new VBK block was found):

```
 Current balance: 0.00081223 BTC
  Minimum required: 0.00001000 BTC, need -0.00080223 BTC more
  Send Bitcoin to: bc1queszxxhq43dr5a97xts4mwp3kd2pv4fqyr888d
        at org.veriblock.miners.pop.service.MinerService.checkReadyConditions(MinerService.kt:248)
        at org.veriblock.miners.pop.service.MinerService.mine(MinerService.kt:268)
        at org.veriblock.miners.pop.automine.AutoMineEngine.mine(AutoMineEngine.kt:66)
        at org.veriblock.miners.pop.automine.AutoMineEngine.onNewVeriBlockFound(AutoMineEngine.kt:56)
        at org.veriblock.miners.pop.automine.AutoMineEngine.access$onNewVeriBlockFound(AutoMineEngine.kt:19)
        at org.veriblock.miners.pop.automine.AutoMineEngine$run$1.invoke(AutoMineEngine.kt:35)
        at org.veriblock.miners.pop.automine.AutoMineEngine$run$1.invoke(AutoMineEngine.kt:19)
        at org.veriblock.core.utilities.Event.trigger(Event.kt:73)
        at org.veriblock.miners.pop.service.NodeCoreService.poll(NodeCoreService.kt:166)
        at org.veriblock.miners.pop.service.NodeCoreService.access$poll(NodeCoreService.kt:28)
        at org.veriblock.miners.pop.service.NodeCoreService$initialize$2$1.invokeSuspend(NodeCoreService.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
        at java.lang.Thread.run(Unknown Source)
```

getdebuginfo shows:

```
getdebuginfo
Running several checks, this may take a few moments...
{
  "information": [
    "SUCCESS - NodeCore connection: Connected to 127.0.0.1:10500",
    "SUCCESS - NodeCore configured network: NodeCore & VPM are running on the same configured network (MainNet)",
    "SUCCESS - NodeCore synchronization status: Synchronized 1 blocks left (LocalHeight=1568476 NetworkHeight=1568475 InitialBlockDownload=false)",
    "SUCCESS - Bitcoin service is ready",
    "SUCCESS - Blockchain download status: Downloaded 100%, 0 blocks to go",
    "FAIL - The BTC PoP wallet does not contain sufficient funds: current balance: 0.00081223 BTC, minimum required: 0.00001000 BTC, need -0.00080223 BTC more."
  ]
```

Workaround to fix this was restarting the VPM

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/ed8353c0c8a372e7b38f4827ef8d15a0ad8567cf, thanks!
